#!/bin/sh

if [ -x "${1}" ]; then
	PTXDIST=${1}
fi
if [ -z "${PTXDIST}" ]; then
        PTXDIST=ptxdist
fi

here="$(cd "$(dirname "$(realpath "${0}")")" && pwd)"

${PTXDIST} --ptxconfig="${here}/configs/ptxconfig" --platformconfig="${here}/configs/platformconfig" --toolchain=/usr/bin bash ptxd_repology
